"""mudança do endereço

Revision ID: 2de9e5c18964
Revises: 08c2c9d0ebb8
Create Date: 2025-11-24 20:28:28.750853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de9e5c18964'
down_revision = '08c2c9d0ebb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.VARCHAR(length=255), nullable=True))

    

    op.drop_table('enderecos')
    # ### end Alembic commands ###
