"""reservas e usuarios

Revision ID: 304c50da2272
Revises: f20f4c824c34
Create Date: 2025-11-20 21:27:49.327008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304c50da2272'
down_revision = 'f20f4c824c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
