"""Adicionando token e linha no user

Revision ID: 32108545c430
Revises: f20f4c824c34
Create Date: 2025-11-19 09:54:20.925760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32108545c430'
down_revision = 'f20f4c824c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=2000), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    # ### end Alembic commands ###
