"""empty message

Revision ID: 5d6620e318a2
Revises: 5fa31ba425f4
Create Date: 2025-11-17 16:42:20.212856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6620e318a2'
down_revision = '5fa31ba425f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_verificacao', sa.String(length=6), nullable=True))

    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.drop_column('foto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.VARCHAR(length=200), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('codigo_verificacao')

    # ### end Alembic commands ###
