"""logradouro

Revision ID: 94d5e0b05cc8
Revises: 2de9e5c18964
Create Date: 2025-11-24 23:48:05.295782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d5e0b05cc8'
down_revision = '2de9e5c18964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logradouro', sa.String(length=150), nullable=False))
        batch_op.drop_column('rua')


    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.VARCHAR(length=255), nullable=True))

   

    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rua', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('logradouro')

    # ### end Alembic commands ###
