"""juntando tudo

Revision ID: e7e474b4ad6a
Revises: 5c11ad7f1e3c
Create Date: 2025-11-25 02:22:46.963381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e474b4ad6a'
down_revision = '5c11ad7f1e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('bairro', sa.String(length=120), nullable=False),
    sa.Column('logradouro', sa.String(length=150), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=150), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.VARCHAR(length=255), nullable=True))

    
    op.drop_table('enderecos')
    # ### end Alembic commands ###
